activation: swish
atom_cutoff: 45
auxcutoff: 0
batch_size: 2
beta: 0.0015
cg_cutoff: 70
cg_method: cgae
cgae_reg_weight: 0.25
dataset: Ca-eIF4E
dec_nconv: 9
dec_type: EquivariantDecoder
edgeorder: 1
enc_nconv: 5
factor: 0.66376
gamma: 2.5
logdir: ./PED_exp
lr: 0.00011
n_basis: 550
n_ensemble: 2
n_rbf: 6
nepochs: 600
nevals: 36
nsamples: 35
optimizer: adam
patience: 25
threshold: 0.001
